services:
  - type: web
    name: stock-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        value: https://tppoclzkphbksluumjbo.supabase.co/
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcG9jbHprcGhia3NsdXVtamJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjk5OTksImV4cCI6MjA2NTY0NTk5OX0.MC9__-qgDP-po_I_PCLjF4o-6Pi9mrQz-4baV0unGqU
